[package]
name = "libretropawn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.147"
libloading = "0.8.0"
libretro-sys = "0.1.1"
thiserror = "1.0.44"
